### ISSUE TITLE
[Major] The filler does not work after a invalid search search

### ISSUE THREAD

**Issue by tran6388-1672747** [FannieFann/Info-442-Global-Souvenir-Guidebook#35]
**Description**
After getting into the web site, I enter an search like "kkk" which will not return any search as I expected. But then, when I click on any of the filter like Food or Book; It return nothing which is not something I expect. For some reason the page to show the results would shut down after a no results show up.

**To Reproduce**
1. go to "http://52.183.24.181:3000/view1"
2. enter "kkk" and click search
3. show no results
4. click food filter.
5. error: see no results in the page which is wrong.

**Expect behavior**
See results after click filter like "food"

**Scene Shot**

![Screenshot (75)](https://user-images.githubusercontent.com/23422230/70366552-f4b05780-184c-11ea-9631-4269d8182d23.png)

![Screenshot (75)](https://user-images.githubusercontent.com/23422230/70366563-0db90880-184d-11ea-8d14-13dcfe1daf84.png)

**Comment by deepforce** [comment]
**Not A ISSUE**
This is because the data in our database are not as large as you think. The filter function and search function are combined together using "AND" logic when users are trying to use them together. In your situation, it's correct to see "No Results" when you are trying to type "kkk", because our search function only search with fulltext keyword. There aren't anything called "kkk" in our database. Likewise, that's why you clicked on "Food" filter, it still came out "No Results".
